downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - TV
  - Podcasts
  - Safari

dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''

# CONFIG OF THE DOTFILES
dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/dotfiles
dotfiles_files:
  - .zshrc

# HOMEBREW CONFIG & INSTALL
homebrew_installed_packages:
  - zsh
  - gpg
  - nvm
  - romkatv/powerlevel10k/powerlevel10k
  - font-meslolgs-nf
  - jetbrains/utils/qodana
  - neovim
  - awscli

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - docker
  - 1password
  - trezor-suite
  - tower
  - spotify
  - jetbrains-toolbox
  - adobe-creative-cloud
  - notion
  - postman
  - font-fira-code
  - flipper
  - nordvpn
  - figma
  - microsoft-teams

# INSTALLING APPS FROM APPLE STORE & UPDATE
mas_upgrade_all_apps: true
mas_installed_apps:
  - { id: 497799835, name: "Xcode (14.0.1)" }
  - { id: 441258766, name: "Magnet (2.9.0)" }
  - { id: 409183694, name: "Keynote (12.1)" }
  - { id: 640199958, name: "Developer (10.1.2)" }
  - { id: 1575220747, name: "Bakery (2.11)" }
  - { id: 899247664, name: "TestFlight (3.2.2)" }
  - { id: 803453959, name: "Slack (4.28.182)" }
  - { id: 585829637, name: "Todoist (8.1.0)" }
  - { id: 409201541, name: "Pages (12.1)" }
  - { id: 1450874784, name: "Transporter (1.2.4)" }
  - { id: 1233965871, name: "ScreenBrush (1.7.8)" }
  - { id: 1496833156, name: "Playgrounds (4.1)" }
  - { id: 1339170533, name: "CleanMyMac-MAS (4.11.3)" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
