- name: Configure Developer host.
  hosts: myhosts
  connection: local
  gather_facts: no
  
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello World
        
    - name: Include Folder Configuration
      include_tasks: tasks/folder.yaml
    
    - name: Include MacOS config
      include_tasks: tasks/macos-config.yaml
      
    - name: Include Homebrew tasks
      include_tasks: tasks/homebrew-apps.yaml

    - name: Include Homebrew Cask tasks
      import_tasks: tasks/homebrew-cask-apps.yaml
    
    - name: Include the Apple Store Apps IDs
      include_vars: vars/applestore-ids.yaml

    - name: Include the Apple Store Apps
      import_tasks: tasks/app-store-apps.yaml
