- name: Configure Developer host.
  hosts: myhosts
  connection: local
  gather_facts: no

  vars_prompt:
    - name: new_hostname
      prompt: "Enter the new hostname for your machine"
      private: no

  tasks:
    - name: Include MacOS config
      tags: setup
      include_tasks: tasks/macos-config.yaml

    - name: Include Homebrew tasks
      tags: setup
      include_tasks: tasks/homebrew-apps.yaml

    - name: Include Homebrew Cask tasks
      tags: setup
      import_tasks: tasks/homebrew-cask-apps.yaml

    - name: Include the Apple Store Apps IDs
      tags: setup
      include_vars: vars/applestore-ids.yaml

    - name: Include the Apple Store Apps
      tags: setup
      import_tasks: tasks/app-store-apps.yaml

    - name: Include Folder Configuration
      tags: setup
      include_tasks: tasks/folder.yaml

    - name: Clone Git Repos
      tags: setup
      include_tasks: tasks/git/git.yaml

    - name: Setup .Dotfiles
      tags: setup
      include_tasks: tasks/dotfiles.yaml