- name: Configure Developer host.
  hosts: myhosts
  connection: local
  gather_facts: no
  
  vars_prompt:
    - name: new_hostname
      prompt: "Enter the new hostname for your machine"
      private: no
  
  tasks:
    - name: Include MacOS config
      include_tasks: tasks/macos-config.yaml
      
    - name: Include Homebrew tasks
      include_tasks: tasks/homebrew-apps.yaml

    - name: Include Homebrew Cask tasks
      import_tasks: tasks/homebrew-cask-apps.yaml
    
    - name: Include the Apple Store Apps IDs
      include_vars: vars/applestore-ids.yaml

    - name: Include the Apple Store Apps
      import_tasks: tasks/app-store-apps.yaml
      
    - name: Include Folder Configuration
      include_tasks: tasks/folder.yaml
    
    - name: Clone Git Repos
      include_tasks: tasks/git/git.yaml
    
    - name: Clone Ask Git Repos
      include_tasks: tasks/git/git-ask.yaml
    
    - name: Clone Arctouch Git Repos
      include_tasks: tasks/git/git-at.yaml
    
    - name: Clone SROA Git Repos
      include_tasks: tasks/git/git-sroa.yaml
