- name: Decrypt specific encrypted files
  tags: setup
  ansible.builtin.command:
    cmd: ansible-vault decrypt {{ item }}
  loop:
    - '~/.dotfiles/.aws/config'
    - '~/.dotfiles/.aws/credentials'
    - '~/.dotfiles/.ssh/id_ed25519'
    - '~/.dotfiles/.ssh/id_ed25519.pub'
    - '~/.dotfiles/.ssh/natura'
    - '~/.dotfiles/.ssh/natura.pub'
    - '~/.dotfiles/gpg-keys/Higor Alves (7E580DB3) – Secret.asc'
  vars_prompt:
    - name: vault_password
      prompt: "Enter the vault password for decryption"
      private: yes

- name: Stow dotfiles
  tags: setup
  ansible.builtin.command:
    cmd: stow -t ~ */
  args:
    chdir: '{{ ansible_env.HOME }}/.dotfiles'