- name: Decrypt specific encrypted files
  tags: setup
  ansible.builtin.command: ansible-vault decrypt {{ item }}
  loop:
    - '~/.dotfiles/.aws/config'
    - '~/.dotfiles/.aws/credentials'
    - '~/.dotfiles/.ssh/id_ed25519'
    - '~/.dotfiles/.ssh/id_ed25519.pub'
    - '~/.dotfiles/.ssh/natura'
    - '~/.dotfiles/.ssh/natura.pub'
    - '~/.dotfiles/gpg-keys/higoralves.asc'

- name: Stow dotfiles
  tags: setup
  ansible.builtin.command: stow -t ~ ~/.dotfiles
  args:
    chdir: '~/.dotfiles'