- name: Ensure Developer and subdirectories exist
  tags: setup
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/Developer"
    - "~/Developer/system"
    - "~/Developer/tools"
    - "~/Developer/templates"
    - "~/Developer/projects"