- name: Install ZSH
  homebrew:
    name: zsh
    state: present

- name: Install Node Version Manager (NVM)
  homebrew:
    name: nvm
    state: present

- name: Install PyEnv
  homebrew:
    name: pyenv
    state: present

- name: Install Watchman
  homebrew:
    name: watchman
    state: present

- name: Install NeoVim (NVim)
  homebrew:
    name: neovim
    state: present

- name: Install fzf Fuzzy Finder
  homebrew:
    name: fzf
    state: present

- name: Install Mas
  homebrew:
    name: mas
    state: present

- name: Install AWS CLI
  homebrew:
    name: awscli
    state: present

- name: Install GNU Stow
  homebrew:
    name: stow
    state: present

- name: Install AWS Logs
  homebrew:
    name: awslogs
    state: present

- name: Install BAT
  homebrew:
    name: bat
    state: present

- name: Install OpenJDK
  homebrew:
    name: openjdk
    state: present

- name: Install StarShip
  homebrew:
    name: starship
    state: present

- name: Install OpenVPN
  homebrew:
    name: openvpn
    state: present

- name: Install zsh syntax highlighting
  homebrew:
    name: zsh-syntax-highlighting
    state: present

- name: Install BTop
  homebrew:
    name: btop
    state: present

- name: Install Lazy Git
  homebrew:
    name: lazygit
    state: present

- name: Install Lazy Docker
  homebrew:
    name: lazydocker
    state: present

- name: Install Gource
  homebrew:
    name: Gource
    state: present

- name: Install Git LFS
  homebrew:
    name: git-lfs
    state: present

- name: Install Codex
  homebrew:
    name: codex
    state: present
