- name: Install ZSH
  homebrew:
    name: zsh
    state: present

- name: Install Node Version Manager (NVM)
  homebrew:
    name: nvm
    state: present

- name: Install Tmux
  homebrew:
    name: tmux
    state: present

- name: Install Watchman
  homebrew:
    name: watchman
    state: present

- name: Install NeoVim (NVim)
  homebrew:
    name: neovim
    state: present

- name: Install Mas
  homebrew:
    name: mas
    state: present

- name: Install AWS CLI
  homebrew:
    name: awscli
    state: present

- name: Install GNU Stow
  homebrew:
    name: stow
    state: present

- name: Install AWS Logs
  homebrew:
    name: awslogs
    state: present

- name: Install BAT
  homebrew:
    name: bat
    state: present

- name: Install OpenJDK
  homebrew:
    name: openjdk
    state: present

- name: Install StarShip
  homebrew:
    name: starship
    state: present

- name: Install Qodana
  homebrew:
    name: jetbrains/utils/qodana
    state: present